apiVersion: containerservice.azure.com/v1api20230201
kind: ManagedCluster
metadata:
  name: asoprodcluswus401
  namespace: default
spec:
  location: westus3
  owner:
    name: aso-prod-clus-wus3
  dnsPrefix: asopc04
  agentPoolProfiles:
    - name: pool1
      count: 1
      vmSize: Standard_DS2_v2
      osType: Linux
      mode: System
  identity:
    type: SystemAssigned

